from utils.operators import *


top_models = {
    "RESCAL": {"embedding_kwargs":{"embedding_dim": 500, "num_epochs":10},
               "embedding_transform":AverageOperator(),
               "classifier_kwargs":{"hidden_layer_sizes":(100,200)},
               "classifier_type": "mlp"},
    "DistMult": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
                 "embedding_transform":RVISConcatenateOperator(),
                 "classifier_kwargs":{"kernel":"poly"},
                 "classifier_type": "svm"},
    "ComplEx": {"embedding_kwargs": {"embedding_dim": 50, "num_epochs": 300},
               "embedding_transform": RVISConcatenateOperator(),
               "classifier_type": "svm", "classifier_kwargs": {"kernel": "poly"}
               },
    "QuatE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
              "embedding_transform":RVISConcatenateOperator(),
              "classifier_kwargs":{"kernel":"poly"},
              "classifier_type": "svm"},
    "TransE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
              "embedding_transform":RVISConcatenateOperator(),
              "classifier_type": "svm", "classifier_kwargs":{"kernel":"poly"}},
    "MuRE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
              "embedding_transform":RVISConcatenateOperator(),
              "classifier_type": "svm", "classifier_kwargs":{"kernel":"poly"}},
    "RotatE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
               "embedding_transform":RVISConcatenateOperator(),
               "classifier_kwargs":{"kernel":"poly"},
               "classifier_type":"svm"},
    "ConvE": {"embedding_kwargs":{"embedding_dim": 400, "num_epochs":20},
              "embedding_transform":AverageOperator(),
              "classifier_kwargs":{"hidden_layer_sizes":(300,50)},
              "classifier_type": "mlp"},
    "Edge2vec": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":20},
                 "embedding_transform":RVISConcatenateOperator(),
                 "classifier_type": "svm", "classifier_kwargs":{"kernel":"poly"}},
    "ERMLP": {"embedding_kwargs":{"embedding_dim": 200, "num_epochs":10},
              "embedding_transform":RVISConcatenateOperator(),
              "classifier_kwargs":{"kernel":"poly"},
              "classifier_type":"svm"}
}

tuned_parameters = {
        "forest": {
            "RESCAL": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":300},
                       "embedding_transform":RVISConcatenateOperator(),
                       "classifier_kwargs":{"n_estimators":460}
                       },
            "DistMult": {"embedding_kwargs":{"embedding_dim":200, "num_epochs":200},
                         "embedding_transform":RVISConcatenateOperator(),
                         "classifier_kwargs":{"n_estimators":300}},
            "ComplEx": {"embedding_kwargs":{"embedding_dim":200, "num_epochs":300},
                        "embedding_transform":RVISConcatenateOperator(),
                        "classifier_kwargs":{"n_estimators":400}},
            "QuatE": {"embedding_kwargs":{"embedding_dim":300, "num_epochs":20},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"n_estimators":500}},
            "MuRE": {"embedding_kwargs":{"embedding_dim":200, "num_epochs":100},
                     "embedding_transform":RVISConcatenateOperator(),
                     "classifier_kwargs":{"n_estimators":200}},
            "TransE": {"embedding_kwargs":{"embedding_dim":400, "num_epochs":50},
                       "embedding_transform":RVISConcatenateOperator(),
                       "classifier_kwargs":{"n_estimators":200}},
            "RotatE": {"embedding_kwargs":{"embedding_dim":400, "num_epochs":50},
                       "embedding_transform":RVISConcatenateOperator(),
                       "classifier_kwargs":{"n_estimators":200}},
            "ConvE": {"embedding_kwargs":{"embedding_dim": 500, "num_epochs":20},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"n_estimators":400}},
            "Edge2vec": {"embedding_kwargs":{"embedding_dim": 500, "num_epochs":10},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"n_estimators":400}},
            "ERMLP": {"embedding_kwargs":{"embedding_dim": 300, "num_epochs":200},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"n_estimators":300}}
        },
        "mlp": {
            "RESCAL": {"embedding_kwargs":{"embedding_dim": 500, "num_epochs":10},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(100,200)}
                       },
            "DistMult": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":100},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(200,)}
                       },
            "ComplEx": {"embedding_kwargs":{"embedding_dim": 500, "num_epochs":20},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(200,)}
                       },
            "QuatE": {"embedding_kwargs":{"embedding_dim": 500, "num_epochs":20},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(100,)},
                      },
            "MuRE": {"embedding_kwargs":{"embedding_dim": 200, "num_epochs":300},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(300,)},
                      },
            "TransE": {"embedding_kwargs":{"embedding_dim": 300, "num_epochs":200},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(300,10)},
                      },
            "RotatE": {"embedding_kwargs":{"embedding_dim": 300, "num_epochs":100},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"hidden_layer_sizes":(200,)},
                      },
            "ConvE": {"embedding_kwargs":{"embedding_dim": 400, "num_epochs":20},
                       "embedding_transform":AverageOperator(),
                      "classifier_kwargs":{"hidden_layer_sizes":(300,50)},
                      },
            "Edge2vec": {"embedding_kwargs":{"embedding_dim": 200, "num_epochs":300},
                       "embedding_transform":AverageOperator(),
                         "classifier_kwargs":{"hidden_layer_sizes":(300,)}},
            "ERMLP": {"embedding_kwargs":{"embedding_dim": 300, "num_epochs":200},
                       "embedding_transform":AverageOperator(),
                         "classifier_kwargs":{"hidden_layer_sizes":(300,)}},
        },
        "svm": {
            "RESCAL": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":100},
                       "embedding_transform":AverageOperator(),
                       "classifier_kwargs":{"kernel":"rbf"}},
            "DistMult": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
                        "embedding_transform":RVISConcatenateOperator(),
                         "classifier_kwargs":{"kernel":"poly"}},
            "ComplEx": {"embedding_kwargs":{"embedding_dim": 50, "num_epochs":300},
                        "embedding_transform":RVISConcatenateOperator(),
                        "classifier_kwargs":{"kernel":"poly"}},
            "QuatE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"kernel":"poly"}},
            "MuRE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
                      "embedding_transform":RVISConcatenateOperator(),
                     "classifier_kwargs":{"kernel":"poly"}},
            "TransE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
                      "embedding_transform":RVISConcatenateOperator(),
                       "classifier_kwargs":{"kernel":"poly"}},
            "RotatE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":200},
                      "embedding_transform":RVISConcatenateOperator(),
                       "classifier_kwargs":{"kernel":"poly"}},
            "ConvE": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":10},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"kernel":"poly"}},
            "Edge2vec": {"embedding_kwargs":{"embedding_dim": 100, "num_epochs":20},
                         "embedding_transform":RVISConcatenateOperator(),
                         "classifier_kwargs":{"kernel":"poly"}},
            "ERMLP": {"embedding_kwargs":{"embedding_dim": 200, "num_epochs":10},
                      "embedding_transform":RVISConcatenateOperator(),
                      "classifier_kwargs":{"kernel":"poly"}}
        }
    }

default_parameters = {"embedding_dim":10,"num_epochs":10,
                      "embedding_transform":RVISConcatenateOperator(),
                      "forest":{"n_estimators":100,"random_state": 10,"sampling_strategy": "auto",
                                "replacement": False},
                      "mlp":{"hidden_layer_sizes":(100,),"random_state": 10,},
                      "svm":{"kernel": "rbf", "random_state": 10}}


total_layers = ["phenotype",
                "biologicalprocess","molecularfunction","cellularcomponent",
                "proteindomain","proteinfamily",
                "proteincomplex",
                "tissue",
                "pathway",
                "seqsimilar","coexpresses","physinteracts"]
num_layers = len(total_layers)

layer_folders = ["Layer1/","Layer2/","Layer3/","Layer4/","Layer5/","Layer6/","Layer7/","Layer8/",
                 "Layer9/","Layer10/",""]